### ISSUE TITLE
버그와 개선점

### ISSUE THREAD

**Issue by hw0k** [tbvjaos510/DesktopCalendar#1]
### 여러 테마 지원
현재는 투명한 모드밖에 없어 검은 배경을 사용하고 있는 사람들에게 굉장히 불편합니다.  
Transparent / Light / Dark 세 가지 모드를 지원해서 쓸 수 있으면 좋을 것 같습니다.  

### 이벤트 추가 이후 추가 창 닫기
간단한 UX 개선 건의합니다.  

### 가끔 앱이 포커스를 벗어나 마우스 입력이 먹지 않음
앱 바깥에 포커스가 맞춰져 있을 때 아무것도 동작하지 않습니다.

**Comment by tbvjaos510** [comment]
1.1버전에 추가하였습니다!
